REVOKE ALL ON ALL FUNCTIONS IN SCHEMA SCHEMA_CATALOG FROM PUBLIC;
REVOKE ALL ON ALL PROCEDURES IN SCHEMA SCHEMA_CATALOG FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA SCHEMA_PROM FROM PUBLIC;
REVOKE ALL ON ALL PROCEDURES IN SCHEMA SCHEMA_PROM FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA SCHEMA_TRACING FROM PUBLIC;
REVOKE ALL ON ALL PROCEDURES IN SCHEMA SCHEMA_TRACING FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA SCHEMA_TRACING_PUBLIC FROM PUBLIC;
REVOKE ALL ON ALL PROCEDURES IN SCHEMA SCHEMA_TRACING_PUBLIC FROM PUBLIC;