# The documentation is at http://goreleaser.com
# Release instructions
# 1) git tag -a 0.1.0-alpha.1 -m "Release 0.1.0-alpha-1"
# 2) goreleaser          //--skip-publish for dry-run
before:
  hooks:
    - go mod download
    #make sure generate up to date
    - go generate ./...


builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/promscale/
  id: promscale
  ldflags:
    - -s -w -X github.com/timescale/promscale/pkg/version.CommitHash={{.Commit}} -X github.com/timescale/promscale/pkg/version.Branch={{.Branch}} -X github.com/timescale/promscale/pkg/telemetry.BuildPlatform=goreleaser
- env:
  - CGO_ENABLED=0
  main: ./cmd/prom-migrator
  dir: migration-tool
  id: prom-migrator
  binary: prom-migrator

#don't publish scoop but overwrite the weird names
scoop:
  name: promscale
  commit_author:
    name: Timescale
    email: support@timescale.com

nfpms:
  - builds:
    - promscale
    formats:
      - rpm
      - deb

    bindir: /usr/bin

    file_name_template: "{{ .Binary }}_{{ .RawVersion }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    description: |
      Promscale is a horizontally scalable and operationally mature analytical
      platform for Prometheus data that offers the combined power of PromQL
      and SQL, enabling developers to ask any question, create any dashboard,
      and achieve greater visibility into their systems.  Promscale is built
      on top of TimescaleDB, the relational database for time-series built on
      top of PostgreSQL.

    license: Apache License 2.0
    maintainer: Timescale <info@timescale.com>
    contents:
      - src: build/systemd/promscale.service
        dst: /usr/lib/systemd/system/promscale.service
      - src: build/conf/promscale.conf
        dst: /etc/sysconfig/promscale.conf
        type: "config|noreplace"
        packager: rpm
      - src: build/env/rpm.env
        dst: /etc/sysconfig/promscale.env
        packager: rpm
      - src: build/conf/promscale.conf
        dst: /etc/promscale.conf
        type: "config|noreplace"
        packager: deb
      - src: build/env/deb.env
        dst: /etc/promscale.env
        packager: deb

    rpm:
      summary: An analytical platform and long-term store for Prometheus
      group: Network Servers

    overrides:
      rpm:
        dependencies:
          - shadow-utils

    scripts:
      preinstall: "build/scripts/preinstall.sh"
      postinstall: "build/scripts/postinstall.sh"
      postremove: "build/scripts/postremove.sh"


archives:
- format: binary
  builds:
  - promscale
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
- id: prom-migrator
  format: binary
  builds:
  - prom-migrator
  name_template: "{{ .Binary }}_0.0.4_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
-
  ids: []
  skip_push: false
  dockerfile: ./build/Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  extra_files: [.git, go.sum, go.mod, pkg, cmd]
  image_templates:
  - "timescale/promscale:{{ .Tag }}-amd64"
-
  ids: []
  skip_push: false
  dockerfile: ./build/Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  extra_files: [.git, go.sum, go.mod, pkg, cmd]
  image_templates:
  - "timescale/promscale:{{ .Tag }}-arm64"
- ids: []
  skip_push: false
  dockerfile: ./build/prom-migrator/Dockerfile
  extra_files:
  - .git
  - go.sum
  - go.mod
  - pkg
  - migration-tool
  image_templates:
  - "timescale/prom-migrator:0.0.4"
  - "timescale/prom-migrator:latest"

docker_manifests:
- name_template: 'timescale/promscale:{{ .Tag }}'
  image_templates:
  - 'timescale/promscale:{{ .Tag }}-amd64'
  - 'timescale/promscale:{{ .Tag }}-arm64'
- name_template: 'timescale/promscale:{{ .Major }}.{{ .Minor }}'
  image_templates:
  - 'timescale/promscale:{{ .Tag }}-amd64'
  - 'timescale/promscale:{{ .Tag }}-arm64'
  # skip_push=auto prevents push for pre-release tags
  skip_push: auto
- name_template: 'timescale/promscale:latest'
  image_templates:
  - 'timescale/promscale:{{ .Tag }}-amd64'
  - 'timescale/promscale:{{ .Tag }}-arm64'
  # skip_push=auto prevents push for pre-release tags
  skip_push: auto

release:
  draft: true
  extra_files:
    - glob: ./dist/rpm/*
