# The documentation is at http://goreleaser.com
# Release instructions
# 1) git tag -a 0.1.0-alpha.1 -m "Release 0.1.0-alpha-1"
# 2) goreleaser          //--skip-publish for dry-run
before:
  hooks:
    # lock file that makes sure rpm is built only once
    - rm -f .buildrpmstarted
    - go mod download
    #make sure generate up to date
    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/promscale/
  hooks:
    # build el8 rpm
    # will be triggered multiple times but we need
    # {{ .Tag }} to ensure same version is used
    post: bash build_rpm.sh {{ .Tag }}

#don't publish scoop but overwrite the weird names
scoop:
  name: promscale
  commit_author:
    name: Timescale
    email: support@timescale.com

archives:
- format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
-
  binaries:
  - promscale
  skip_push: false
  extra_files:
  - .git
  - go.sum
  - go.mod
  - pkg
  - cmd
  image_templates:
  - "timescale/promscale:{{ .Tag }}"
  - "timescale/promscale:{{ .Major }}.{{ .Minor }}"
  - "timescale/promscale:latest"

release:
  extra_files:
    - glob: ./dist/rpm/*