CREATE TYPE SCHEMA_TAG.tag_op_jsonb_path_exists AS (tag_key text, value jsonpath);
CREATE TYPE SCHEMA_TAG.tag_op_regexp_matches AS (tag_key text, value text);
CREATE TYPE SCHEMA_TAG.tag_op_regexp_not_matches AS (tag_key text, value text);
CREATE TYPE SCHEMA_TAG.tag_op_equals AS (tag_key text, value jsonb);
CREATE TYPE SCHEMA_TAG.tag_op_not_equals AS (tag_key text, value jsonb);
CREATE TYPE SCHEMA_TAG.tag_op_less_than AS (tag_key text, value jsonb);
CREATE TYPE SCHEMA_TAG.tag_op_less_than_or_equal AS (tag_key text, value jsonb);
CREATE TYPE SCHEMA_TAG.tag_op_greater_than AS (tag_key text, value jsonb);
CREATE TYPE SCHEMA_TAG.tag_op_greater_than_or_equal AS (tag_key text, value jsonb);
