apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
{{ include "promscale-helm.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "0"
data:
  config.yaml: |
{{ toYaml .Values.config | nindent 4 }}
