apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
{{ include "promscale-helm.labels" . | indent 4 }}

