{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
{{ include "promscale-helm.labels" . | indent 4 }}
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
    path: /metrics
  selector:
    matchLabels:
{{ include "promscale.labels" . | indent 6 }}
{{- end }}
