version: '3.0'

services:
  db:
    image: timescaledev/promscale-extension:latest-pg12
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: timescale

  prometheus1:
    image: prom/prometheus:latest
    ports:
      - 9091:9090/tcp
    volumes:
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml:ro

  prometheus2:
    image: prom/prometheus:latest
    ports:
      - 9092:9090/tcp
    volumes:
      - ./prometheus2.yml:/etc/prometheus/prometheus.yml:ro

  promscale-connector1:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
      - prometheus1
    environment:
      TS_PROM_LEADER_ELECTION_PG_ADVISORY_LOCK_ID: 1
      TS_PROM_LEADER_ELECTION_PG_ADVISORY_LOCK_PROMETHEUS_TIMEOUT: 30s
      TS_PROM_LOG_LEVEL: info
      TS_PROM_DB_CONNECT_RETRIES: 10
      TS_PROM_DB_HOST: db
      TS_PROM_DB_PASSWORD: postgres
      TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
      TS_PROM_DB_SSL_MODE: allow

  promscale-connector2:
    image: timescale/promscale:latest
    ports:
      - 9202:9201/tcp
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
      - prometheus2
    environment:
      TS_PROM_LEADER_ELECTION_PG_ADVISORY_LOCK_ID: 1
      TS_PROM_LEADER_ELECTION_PG_ADVISORY_LOCK_PROMETHEUS_TIMEOUT: 30s
      TS_PROM_LOG_LEVEL: info
      TS_PROM_DB_CONNECT_RETRIES: 10
      TS_PROM_DB_HOST: db
      TS_PROM_DB_PASSWORD: postgres
      TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
      TS_PROM_DB_SSL_MODE: allow