apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . | trunc 51 }}-maintenance
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  execute_maintenance.sh: |-
    #!/bin/sh
    psql  \
    {{ if .Values.connection.uri.secretTemplate -}} $PROMSCALE_DB_URI \{{- end }}
    -e -q -c "CALL prom_api.execute_maintenance();"
    if [ $? -eq 0 ]
    then
      echo "Maintenance completed successfully."
      echo "Retention policies executed."
    else
      echo "Maintenance job failed!"
    fi