apiVersion: v1
kind: Service
metadata:
  name: {{ include "promscale.fullname" . | trunc 53 }}-connector
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ .Values.service.loadBalancer.annotations | toYaml | indent 4 }}
spec:
  selector:
    app: {{ template "promscale.fullname" . }}
{{- if .Values.service.loadBalancer.enabled }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
  - name: metrics-port
    port: {{ .Values.service.metricsPort }}
    protocol: TCP
  {{ if .Values.tracing.enabled }}
  - name: traces-port
    port: {{ .Values.service.tracesPort }}
    protocol: TCP
  {{- end }}
