apiVersion: v1
kind: Service
metadata:
  name: {{ template "clusterName" . }}-adapter
  labels:
    app: {{ template "timescaledb.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
spec:
  selector:
    app: {{ .Release.Name }}-adapter
  type: LoadBalancer
  ports:
  - name: adapter-port
    port: 9201
    protocol: TCP
