name: Go Report Card

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

on:
  push:
    branches: [master, main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Request Report Update
        run: |
          curl -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks
